openapi: 3.0.1
info:
  title: Bedrock Jenkins Analyzer
  version: 1.0.0
paths:
  /invoke:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                log:
                  type: string
      responses:
        '200':
          description: AI analysis response
